### ISSUE TITLE
Support for Echo v5

### ISSUE THREAD

**Issue by kisamoto** [samber/slog-echo#12]
Is it possible to support echo v5?

i.e. 

With echo you can currently `import "github.com/labstack/echo/v5"` however this is incompatible with slog-echo which expects v4.

**Comment by kisamoto** [comment]
Can you create a branch for echo v5 please? 

I have a PR branch ready: https://github.com/kisamoto/slog-echo

**Comment by samber** [comment]
It looks good 👌 

![image](https://github.com/samber/slog-echo/assets/2951285/d16514a8-06ec-4179-bb17-1fc0109660c1)
