### ISSUE TITLE
Duplicate time in logs

### ISSUE THREAD

**Issue by Snaipe** [samber/slog-echo#16]
When using the middleware, the time key is duplicated:

```go
logger := slog.New(slog.NewJSONHandler(os.Stderr, nil))

e := echo.New()

config := slogecho.Config{
	WithRequestBody: true,
	WithRequestHeader: true,
	WithResponseHeader: true,
	WithSpanID:  true,
	WithTraceID: true,
}
e.Use(slogecho.NewWithConfig(logger, config))
```

```
{"time":"2023-11-20T21:08:54.385775304+01:00","level":"INFO","msg":"example","time":"2023-11-20T21:08:54.385747657+01:00","latency":180617,"method":"GET","path":"/example","route":"/example","status":404,"ip":"::1","user-agent":"curl/8.4.0","trace-id":"0a9a35e5aec25e80a4777bed077ea2f1","span-id":"975848c3ee022956","request":{"body":""},"request":{"header":{"User-Agent":["curl/8.4.0"]}},"request":{"header":{"Accept":["*/*"]}},"response":{"header":{"Content-Type":["application/json; charset=UTF-8"]}}}
```

**Comment by drmaples** [comment]
😢 i just spotted this myself

**Comment by jtarchie** [comment]
I just noticed this myself. When using the JSON formatter it is inserting the `time` tag itself.

**Comment by samber** [comment]
Yes, this "time" is inserted by the final handler that format and eventually transfer the log to a sink.

It is the time of the `slog.Error()` call. The "time" provided by this middleware is the time of the response.

Most of time it will be identicical.

**Comment by Snaipe** [comment]
I'm not certain the distinction brings value; in the middleware, the time of response is really the [approximate time after the next handling function returns](https://github.com/samber/slog-echo/blob/main/middleware.go#L140) rather that the time the response was started to get written, or the time that the response ended. 100 lines below, the [logger is called](https://github.com/samber/slog-echo/blob/main/middleware.go#L255), and between the two time samples, there are mostly only conditions and append operations, which shouldn't take much time.

So, I'm inclined to believe that these two times are effectively interchangeable (with a difference in the ns-ms range). If that's the case, why bother providing a second time value? I would honestly consider removing the time that the middleware provides and just rely on the log handler to do this, just like the json handler does.

But ultimately, this isn't the problem that this issue raises, the problem is that there are duplicate keys in the json payload. The json spec allows (but discourages) this, and while most parser implementations silently ignores this and makes the latter key win, there are some that outright reject these (I think the java impl is notable for this).

I can maybe see three paths here:

1. make the inclusion of the middleware "time" key an option, but this feels like a cop-out
2. if the distinction between the two times is valuable, rename "time" to "response_time" or something of that vein. Calling this the "response time" however isn't really accurate, and may cause confusions.
3. remove the time altogether, since it's the responsibility of the log handler.

**Comment by samber** [comment]
I made some improvements today on the log record format, for another PR. Example below:

```js
{
    "time": "xyz",   // from handler
    "request": {
        "time": "xyz", // request time, from middleware
        "path": "/hello/world",
        ...
    },
    "response": {
        "time": "xyz", // response time, from middleware
        "duration": "10ms",
        "status": 200,
        ...
    },
    ...
}
```

I consider this might be a good solution for this issue.

It solves the duplicate keys problem as well.

**Comment by Snaipe** [comment]
That seems like a good solution to me.
