### ISSUE TITLE
interface conversion: *slogecho.bodyWriter is not http.Hijacker: missing method Hijack

### ISSUE THREAD

**Issue by kluzzebass** [samber/slog-echo#20]
I'm trying to use the `slog-echo` handler in combination with the GraphQL library `gqlgen`. When a client tries to set up a GraphQL subscription, this touches upon some `echo` code that deals with upgrading the HTTP connection to a Websocket connection. There's a lot of stuff going on here, but ultimately, this ends up with `echo` trying to assert `http.Hijacker` and call the `Hijack()` method on a `slogecho.bodyWriter` instance. Unfortunately, this struct doesn't implement that particular function, leading to panic.

The assertion and subsequent call is located here:

https://github.com/labstack/echo/blob/60fc2fb1b76f5613fc41aa9315cad6e8c96c6859/response.go#L94

**Comment by samber** [comment]
hey @kluzzebass 

Thanks for the report. I just made a fix -> v1.12.0

bodyWriter now implements http.ResponseWriter + http.Hijacker + http.Flusher ;)
