### ISSUE TITLE
Internal error is ignored

### ISSUE THREAD

**Issue by aweis89** [samber/slog-echo#21]
When return an echo.HTTPError, the Internal error should be logged but only the Message field sent to the client is actually getting logged

**Comment by dowglaz** [comment]
Hey, just an enthusiast here, not a maintainer. I found something strange when I was testing it. When I write echo returns like:
```go
return &echo.HTTPError{
    Code: http.StatusInternalServerError,
    Message: err,
    Internal: err,
}
```
It just logs everything. `Message` has type `interface{}`, so it handles `string` and `error` differently. So, I don't know if it really helps, but doing something like:
```go
return &echo.HTTPError{
    Code: http.StatusInternalServerError,
    Message: errors.New("public message"),
    Internal: fmt.Errorf("more private details: %w", err),
}
```
Could help your use case too.

It can also be done like this:
 ```go
return echo.NewHTTPError(http.StatusInternalServerError, err).SetInternal(internalErr)
```
