### ISSUE TITLE
Consider AddSource in HandlerOptions

### ISSUE THREAD

**Issue by coin-au-carre** [samber/slog-echo#23]
AddSource provides callstack informations which is proposed by slog https://pkg.go.dev/golang.org/x/exp/slog#HandlerOptions.
However a different depth must be used because the `slog-echo/middleware.go:285` is always referred to

```
7:24PM DBG slog-echo/middleware.go:285 Incoming request request.time="2024-03-06 19:24:10.452642353 +0100 CET" request.method=GET request.host=localhost:8080 request.path=/ request.query="" request.params=map[] request.route=/ request.ip=127.0.0.1 request.referer="" request.length=0 response.time="2024-03-06 19:24:10.452687598 +0100 CET" response.latency=45.245µs response.status=200 response.length=0
7:24PM DBG slog-echo/middleware.go:285 Incoming request request.time="2024-03-06 19:24:10.470362643 +0100 CET" request.method=GET request.host=localhost:8080 request.path=/assets/css/main.css request.query="" request.params=map[*:/css/main.css] request.route=/assets* request.ip=127.0.0.1 request.referer=http://localhost:8080/ request.length=0 response.time="2024-03-06 19:24:10.470477768 +0100 CET" response.latency=115.125µs response.status=304 response.length=0
```

**Comment by samber** [comment]
Hello @coin-au-carre 

I would say that it must be handled by your final slog handler.

Your `AddSource` parameter is given to the stdlib, not slog-echo.

**Comment by coin-au-carre** [comment]
Thanks for the answer. 
Right if I understand this line https://github.com/samber/slog-echo/blob/main/middleware.go#L285 is triggered. 
```
logger.LogAttrs(c.Request().Context(), level, msg, attributes...)
```

I think it would be nice to have a documentation on how to tweak the handler in order to manage `AddSource` with `slog-echo`. If I find a solution I would be glad to share it.

**Comment by samber** [comment]
Check the minimal implementation in readme: https://github.com/samber/slog-echo?tab=readme-ov-file#minimal

```go
logger := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{AddSource: true}))
```
